import type { CreateDraftData, CreateDraftFeature } from "./schemas";

export const draftDefaults: { [K in CreateDraftFeature]: CreateDraftData<K> } = {
  materials: {
    name: "",
    unit: "kg",
    stock: "",
    alertThreshold: "",
    cost: "",
    contentPerUnit: "",
    contentUnit: "",
    notes: "",
    icon: null,
    supplierId: null,
  },
  packaging: { name: "", type: "box", unitCost: "", supplierId: null },
  suppliers: {
    name: "",
    category: "supplies",
    phone: "",
    hasWhatsApp: false,
    email: "",
    address: "",
    purchaseDescription: "",
    isPreferred: false,
    avatarPresetId: null,
  },
  recipes: {
    name: "",
    category: "",
    instructions: "",
    yieldQuantity: "",
    yieldUnit: "",
    step: 1,
    lines: [{ materialId: "", quantity: "", unit: "" }],
  },
  quotes: {
    title: "",
    clientId: null,
    clientName: "",
    validUntil: "",
    notes: "",
    discountType: null,
    discountValue: "",
    formStep: 1,
    items: [{ description: "", quantity: "1", unitPrice: "", estimatedUnitCost: "" }],
  },
  labels: {
    name: "",
    templateId: "classico",
    labelData: { productName: "" },
    selectedProductId: null,
    includeQr: false,
    formStep: 1,
  },
  recurring: { description: "", amount: "", category: "utility", day: "" },
};
export const draftFixtures: { [K in CreateDraftFeature]: CreateDraftData<K> } = {
  materials: {
    ...draftDefaults.materials,
    name: "Farinha QA",
    stock: "1,5",
    cost: "4,50",
  },
  packaging: {
    ...draftDefaults.packaging,
    name: "Pote QA",
    type: "pot",
    unitCost: "2,50",
  },
  suppliers: {
    ...draftDefaults.suppliers,
    name: "Fornecedor QA",
    phone: "(11) 90000-0000",
    email: "qa@example.invalid",
    address: "Endereço sintético",
  },
  recipes: {
    ...draftDefaults.recipes,
    name: "Massa QA",
    category: "Doces",
    yieldQuantity: "1,5",
    yieldUnit: "kg",
    step: 3,
    lines: [{ materialId: "material-qa", quantity: "0,5", unit: "kg" }],
  },
  quotes: {
    ...draftDefaults.quotes,
    title: "Proposta QA",
    formStep: 3,
    items: [
      {
        description: "Marmita QA",
        quantity: "2",
        unitPrice: "25,50",
        estimatedUnitCost: "10,00",
      },
    ],
  },
  labels: {
    ...draftDefaults.labels,
    name: "Etiqueta QA",
    selectedProductId: "produto-qa",
    formStep: 2,
    labelData: {
      productName: "Marmita QA",
      manufacturingDate: "01/10/2026",
      expirationDate: "03/10/2026",
    },
  },
  recurring: {
    ...draftDefaults.recurring,
    description: "Aluguel QA",
    amount: "120,50",
    day: "15",
  },
};
