import { fonts, radii, spacing } from "@lucro-caseiro/ui";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  row: { flexDirection: "row", alignItems: "center" },
  rowBetween: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: spacing.md,
  },
  center: { alignItems: "center", justifyContent: "center" },
  card: { borderWidth: 1, borderRadius: 22 },
  wine: { borderRadius: radii["2xl"], gap: 14 },
  primary: {
    borderRadius: radii.lg,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingHorizontal: spacing.xl,
  },
  primaryLabel: { fontFamily: fonts.bold, fontSize: 17, lineHeight: 22 },
  ghost: { flexDirection: "row", alignItems: "center", gap: 4 },
  ghostLabel: { fontFamily: fonts.bold, fontSize: 16, lineHeight: 22 },
  ghostSmall: { fontFamily: fonts.bold, fontSize: 15, lineHeight: 20 },
  h2Phone: { fontFamily: fonts.extraBold, fontSize: 19, lineHeight: 25 },
  h2Desk: {
    fontFamily: fonts.extraBold,
    fontSize: 26,
    lineHeight: 32,
    letterSpacing: -0.4,
  },
  h3: { fontFamily: fonts.extraBold, fontSize: 19, lineHeight: 25 },
  sectionTitle: { fontFamily: fonts.extraBold, fontSize: 17, lineHeight: 23 },
  body: { fontFamily: fonts.regular, fontSize: 16, lineHeight: 23 },
  bodyBold: { fontFamily: fonts.bold, fontSize: 16, lineHeight: 22 },
  bodyStrong: {
    fontFamily: fonts.extraBold,
    fontSize: 16,
    lineHeight: 22,
    fontVariant: ["tabular-nums"],
  },
  caption: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 19 },
  caption15: { fontFamily: fonts.regular, fontSize: 15, lineHeight: 21 },
  tag: { fontFamily: fonts.bold, fontSize: 13, letterSpacing: 0.4 },
  ringLabel: { fontFamily: fonts.extraBold, fontSize: 14, fontVariant: ["tabular-nums"] },
  step: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 14,
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
  },
  stepDot: {
    width: 36,
    height: 36,
    borderRadius: radii.full,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  stepNumber: { fontFamily: fonts.extraBold, fontSize: 16 },
  stepTitle: { fontFamily: fonts.bold, fontSize: 17, lineHeight: 24 },
  stepTitleDesk: { fontFamily: fonts.bold, fontSize: 18, lineHeight: 24 },
  strike: { textDecorationLine: "line-through" },
  stepButton: { alignSelf: "flex-start", marginTop: 10, paddingHorizontal: 22 },
  example: {
    borderRadius: radii.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
  },
  tiles: { flexDirection: "row", gap: 10 },
  tile: { flex: 1, minWidth: 0, borderRadius: radii.lg, gap: 4 },
  tileLabel: { fontFamily: fonts.regular, fontSize: 14, lineHeight: 19 },
  tileValue: {
    fontFamily: fonts.extraBold,
    fontSize: 26,
    lineHeight: 32,
    fontVariant: ["tabular-nums"],
  },
  tileValueTight: { fontSize: 16, lineHeight: 22, letterSpacing: -0.2 },
  tileValueCompact: {
    fontFamily: fonts.extraBold,
    fontSize: 18,
    lineHeight: 24,
    fontVariant: ["tabular-nums"],
  },
  tileNote: { fontFamily: fonts.regular, fontSize: 13, lineHeight: 17 },
  lastSale: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingTop: 10,
    borderTopWidth: 1,
  },
  time: {
    fontFamily: fonts.regular,
    fontSize: 14,
    minWidth: 44,
    fontVariant: ["tabular-nums"],
  },
  lastSaleName: { flex: 1, minWidth: 0, fontFamily: fonts.semiBold, fontSize: 16 },
  chip: { borderRadius: radii.full, paddingHorizontal: 9, paddingVertical: 3 },
  chipLabel: { fontFamily: fonts.bold, fontSize: 13 },
  bannerTitle: {
    fontFamily: fonts.extraBold,
    fontSize: 21,
    lineHeight: 27,
    letterSpacing: -0.4,
  },
  bannerTitleDesk: {
    fontFamily: fonts.extraBold,
    fontSize: 26,
    lineHeight: 32,
    letterSpacing: -0.4,
  },
  bannerBody: { fontFamily: fonts.regular, fontSize: 16, lineHeight: 22 },
  bannerStrong: { fontFamily: fonts.extraBold },
  bannerSteps: {
    flexWrap: "wrap",
    columnGap: 18,
    rowGap: spacing.sm,
    paddingTop: spacing.md,
    borderTopWidth: 1,
  },
  bannerStep: { fontFamily: fonts.bold, fontSize: 15, lineHeight: 21, flexShrink: 1 },
  idea: {
    minHeight: 64,
    borderWidth: 1,
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: radii.full,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  pillLabel: { fontFamily: fonts.bold, fontSize: 14, lineHeight: 19 },
  heroTitle: { fontFamily: fonts.bold, fontSize: 16, lineHeight: 22 },
  heroValues: { flexDirection: "row", flexWrap: "wrap", rowGap: spacing.md },
  heroLabel: { fontFamily: fonts.regular, fontSize: 15, lineHeight: 21 },
  heroLabelStrong: { fontFamily: fonts.extraBold },
  heroValue: {
    fontFamily: fonts.extraBold,
    fontSize: 30,
    lineHeight: 34,
    letterSpacing: -1,
    fontVariant: ["tabular-nums"],
  },
  heroValueDesk: {
    fontFamily: fonts.extraBold,
    fontSize: 40,
    lineHeight: 44,
    letterSpacing: -1,
    fontVariant: ["tabular-nums"],
  },
  heroWeek: { paddingTop: 14, borderTopWidth: 1, gap: 10 },
  bars: { flexDirection: "row", gap: spacing.sm, alignItems: "flex-end" },
  barCol: { flex: 1, alignItems: "center", justifyContent: "flex-end", gap: 6 },
  barLabel: { fontFamily: fonts.semiBold, fontSize: 13, lineHeight: 18 },
  barLabelToday: { fontFamily: fonts.extraBold, fontSize: 13, lineHeight: 18 },
  stat: {
    flex: 1,
    borderRadius: radii.lg,
    paddingVertical: spacing.md,
    paddingHorizontal: 14,
    gap: 2,
  },
  statValue: {
    fontFamily: fonts.extraBold,
    fontSize: 22,
    lineHeight: 28,
    fontVariant: ["tabular-nums"],
  },
  goalValue: { fontFamily: fonts.bold, fontSize: 15, fontVariant: ["tabular-nums"] },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: 10,
    borderTopWidth: 1,
  },
  rank: {
    width: 28,
    height: 28,
    borderRadius: radii.full,
    alignItems: "center",
    justifyContent: "center",
  },
  rankLabel: { fontFamily: fonts.extraBold, fontSize: 14 },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: radii.full,
    alignItems: "center",
    justifyContent: "center",
  },
  whatsapp: {
    marginTop: spacing.sm,
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
});
