// Catálogo de ilustrações de insumo/produto (fallback emoji + cor).
// Sincronizado de tools/asset-forge/seeds/ingredients.json — quando o
// asset-forge publicar os PNGs, o avatar passa a exibir a imagem pelo slug.

export interface IngredientEntry {
  readonly slug: string;
  readonly label: string;
  readonly emoji: string;
  readonly color: string;
  readonly aliases: readonly string[];
}

export const INGREDIENT_CATALOG: readonly IngredientEntry[] = [
  {
    slug: "acucar",
    label: "Açúcar refinado",
    emoji: "🍬",
    color: "#C9A36A",
    aliases: [
      "acucar",
      "acucar refinado",
      "acucar cristal",
      "acucar de confeiteiro",
      "acucar mascavo",
      "acucar demerara",
    ],
  },
  {
    slug: "farinha-de-trigo",
    label: "Farinha de trigo",
    emoji: "🌾",
    color: "#D8B36A",
    aliases: ["farinha", "farinha de trigo", "trigo", "farinha de rosca"],
  },
  {
    slug: "amido-de-milho",
    label: "Amido de milho",
    emoji: "🌽",
    color: "#E0C66B",
    aliases: ["amido de milho", "amido", "maisena"],
  },
  {
    slug: "fermento",
    label: "Fermento",
    emoji: "🫧",
    color: "#CBB892",
    aliases: ["fermento", "fermento quimico", "fermento biologico", "bicarbonato"],
  },
  {
    slug: "chocolate-em-po",
    label: "Chocolate em pó",
    emoji: "🍫",
    color: "#7B4A2E",
    aliases: ["chocolate em po", "cacau em po", "cacau", "achocolatado", "chocolate"],
  },
  {
    slug: "chocolate-barra",
    label: "Chocolate em barra",
    emoji: "🍫",
    color: "#5E3A24",
    aliases: [
      "chocolate em barra",
      "chocolate barra",
      "barra de chocolate",
      "chocolate ao leite",
      "chocolate meio amargo",
      "cobertura",
      "cobertura de chocolate",
    ],
  },
  {
    slug: "granulado",
    label: "Granulado",
    emoji: "✨",
    color: "#8C5A45",
    aliases: ["granulado", "confeito", "confeitos", "chocolate granulado"],
  },
  {
    slug: "leite",
    label: "Leite",
    emoji: "🥛",
    color: "#6E93B5",
    aliases: ["leite", "leite integral", "leite desnatado", "leite semidesnatado"],
  },
  {
    slug: "leite-condensado",
    label: "Leite condensado",
    emoji: "🥫",
    color: "#7FA8C9",
    aliases: ["leite condensado", "leite moca", "moca"],
  },
  {
    slug: "creme-de-leite",
    label: "Creme de leite",
    emoji: "🥛",
    color: "#9BB7D4",
    aliases: ["creme de leite", "creme leite", "nata"],
  },
  {
    slug: "leite-em-po",
    label: "Leite em pó",
    emoji: "🥛",
    color: "#A9C0D6",
    aliases: ["leite em po", "leite po"],
  },
  {
    slug: "coco",
    label: "Coco ralado",
    emoji: "🥥",
    color: "#B79C84",
    aliases: ["coco", "coco ralado", "leite de coco"],
  },
  {
    slug: "aveia",
    label: "Aveia",
    emoji: "🌾",
    color: "#C7AE83",
    aliases: ["aveia", "farinha de aveia", "flocos de aveia"],
  },
  {
    slug: "manteiga",
    label: "Manteiga",
    emoji: "🧈",
    color: "#D9A441",
    aliases: ["manteiga", "margarina"],
  },
  {
    slug: "queijo",
    label: "Queijo",
    emoji: "🧀",
    color: "#E0B84A",
    aliases: ["queijo", "requeijao", "queijo ralado", "parmesao", "mussarela"],
  },
  {
    slug: "ovo",
    label: "Ovos",
    emoji: "🥚",
    color: "#D8C9A8",
    aliases: ["ovo", "ovos", "ovo de galinha", "clara", "gema"],
  },
  {
    slug: "oleo",
    label: "Óleo",
    emoji: "🫗",
    color: "#C7B45A",
    aliases: ["oleo", "oleo de soja", "oleo vegetal"],
  },
  {
    slug: "agua",
    label: "Água",
    emoji: "💧",
    color: "#6FB0C9",
    aliases: ["agua", "agua mineral"],
  },
  {
    slug: "essencia",
    label: "Essência / Baunilha",
    emoji: "🧴",
    color: "#B79BD4",
    aliases: ["essencia", "baunilha", "aroma", "essencia de baunilha"],
  },
  {
    slug: "sal",
    label: "Sal",
    emoji: "🧂",
    color: "#AEB7BD",
    aliases: ["sal", "sal refinado"],
  },
  { slug: "mel", label: "Mel", emoji: "🍯", color: "#D9A441", aliases: ["mel"] },
  {
    slug: "geleia",
    label: "Geleia / Doce",
    emoji: "🍯",
    color: "#C4566B",
    aliases: ["geleia", "doce", "doce de fruta", "compota"],
  },
  {
    slug: "doce-de-leite",
    label: "Doce de leite",
    emoji: "🍮",
    color: "#A06A3B",
    aliases: ["doce de leite"],
  },
  {
    slug: "nutella",
    label: "Creme de avelã",
    emoji: "🍫",
    color: "#6E4630",
    aliases: ["nutella", "creme de avela", "avela"],
  },
  {
    slug: "morango",
    label: "Morango",
    emoji: "🍓",
    color: "#C4566B",
    aliases: ["morango", "morangos"],
  },
  {
    slug: "banana",
    label: "Banana",
    emoji: "🍌",
    color: "#D9B94A",
    aliases: ["banana", "bananas"],
  },
  {
    slug: "limao",
    label: "Limão",
    emoji: "🍋",
    color: "#C5C24A",
    aliases: ["limao", "limoes", "suco de limao"],
  },
  {
    slug: "laranja",
    label: "Laranja",
    emoji: "🍊",
    color: "#D98A3D",
    aliases: ["laranja", "suco de laranja"],
  },
  {
    slug: "fruta",
    label: "Frutas",
    emoji: "🍓",
    color: "#C4566B",
    aliases: ["fruta", "frutas", "maracuja", "abacaxi", "uva"],
  },
  {
    slug: "cafe",
    label: "Café",
    emoji: "☕",
    color: "#6E4630",
    aliases: ["cafe", "cafe em po", "cafe soluvel"],
  },
  {
    slug: "caixa",
    label: "Caixa",
    emoji: "📦",
    color: "#5E8C61",
    aliases: [
      "caixa",
      "caixinha",
      "caixa para bolo",
      "caixa de bolo",
      "embalagem",
      "caixa de doce",
    ],
  },
  {
    slug: "forma",
    label: "Forma / Forminha",
    emoji: "🧁",
    color: "#7FA86A",
    aliases: ["forma", "forminha", "forminhas", "forma de papel", "forma de bolo"],
  },
  {
    slug: "sacola",
    label: "Sacola",
    emoji: "🛍️",
    color: "#5E8C61",
    aliases: ["sacola", "saco", "saquinho", "saco plastico"],
  },
  {
    slug: "pote",
    label: "Pote",
    emoji: "🫙",
    color: "#6F9BA8",
    aliases: ["pote", "potinho", "potes", "pote plastico"],
  },
  {
    slug: "fita",
    label: "Fita / Laço",
    emoji: "🎀",
    color: "#C4707E",
    aliases: ["fita", "laco", "fita de cetim"],
  },
  {
    slug: "colher",
    label: "Colher",
    emoji: "🥄",
    color: "#9AA0A6",
    aliases: ["colher", "colherzinha", "colher descartavel"],
  },
  {
    slug: "vela",
    label: "Vela",
    emoji: "🕯️",
    color: "#D9A441",
    aliases: ["vela", "velas", "vela de aniversario"],
  },
];
