import type { MarketingResourceInput } from "@lucro-caseiro/contracts";

export const initialMarketingResources: MarketingResourceInput[] = [
  {
    kind: "audience",
    slug: "mercado-lucro-caseiro",
    title: "Mercado amplo do Lucro Caseiro",
    summary:
      "Profissionais e negócios de diferentes segmentos e estágios que precisam precificar, vender e organizar a operação.",
    status: "active",
    data: {
      scope: "brand-market",
      includes: [
        "profissionais autônomos",
        "MEIs",
        "prestadores de serviço",
        "produtores",
        "comerciantes",
        "equipes e negócios em crescimento",
      ],
      maturity: ["início", "operação organizada", "negócio estruturado", "crescimento"],
      rule: "Os públicos de nicho são recortes de campanha e não limitam o mercado da marca.",
    },
  },
  {
    kind: "audience",
    slug: "confeiteiras-iniciantes",
    title: "Confeiteiras iniciantes",
    summary: "Produzem e vendem, mas ainda formam preço no improviso.",
    status: "active",
    data: {
      pains: [
        "medo de cobrar caro",
        "não sabe separar custo e lucro",
        "vende e o dinheiro some",
      ],
      promise: "descobrir o preço certo em poucos minutos",
      channels: ["instagram", "tiktok", "whatsapp"],
      awareness: "problem-aware",
    },
  },
  {
    kind: "audience",
    slug: "artesaos-e-personalizados",
    title: "Artesãos e personalizados",
    summary: "Precisam incluir material, tempo e margem sem planilhas complicadas.",
    status: "active",
    data: {
      pains: ["esquece custos pequenos", "não cobra mão de obra", "orçamento demora"],
      promise: "transformar custo e tempo em preço lucrativo",
      channels: ["instagram", "tiktok", "youtube"],
    },
  },
  {
    kind: "audience",
    slug: "marmitas-e-alimentos",
    title: "Marmitas e alimentos",
    summary: "Têm custos variáveis, rendimento e desperdício difíceis de acompanhar.",
    status: "active",
    data: {
      pains: ["ingredientes mudam de preço", "rendimento incerto", "margem apertada"],
      promise: "proteger a margem mesmo com custo variando",
      channels: ["instagram", "youtube", "whatsapp"],
    },
  },
  {
    kind: "audience",
    slug: "beleza-e-servicos",
    title: "Profissionais de beleza e serviços",
    summary: "Precisam valorizar tempo, insumos e capacidade da agenda.",
    status: "active",
    data: {
      pains: [
        "cobra olhando concorrente",
        "agenda cheia sem lucro",
        "não calcula custo por atendimento",
      ],
      promise: "cobrar com segurança e lucrar por hora",
      channels: ["instagram", "tiktok", "local"],
    },
  },
  {
    kind: "audience",
    slug: "empreendedoras-organizando-negocio",
    title: "Empreendedoras organizando o negócio",
    summary: "Já vendem e querem centralizar preço, pedidos, clientes e finanças.",
    status: "active",
    data: {
      pains: ["anotações espalhadas", "retrabalho", "não sabe o lucro real"],
      promise: "sair do improviso e gerir em um só lugar",
      channels: ["instagram", "youtube", "email"],
    },
  },
  {
    kind: "feature",
    slug: "precificacao",
    title: "Precificação guiada",
    summary: "Calcula custo, margem e preço de venda.",
    status: "active",
    data: {
      audiences: [
        "confeiteiras-iniciantes",
        "artesaos-e-personalizados",
        "marmitas-e-alimentos",
        "beleza-e-servicos",
      ],
      angle: "Pare de chutar preço",
      proof: "mostre o cálculo na tela",
      cta: "Calcule seu primeiro produto",
    },
  },
  {
    kind: "feature",
    slug: "catalogo",
    title: "Catálogo público",
    summary: "Transforma produtos cadastrados em vitrine compartilhável sem recadastro.",
    status: "active",
    data: {
      audiences: [
        "confeiteiras-iniciantes",
        "artesaos-e-personalizados",
        "empreendedoras-organizando-negocio",
      ],
      angle: "Cadastre uma vez, divulgue sempre",
      cta: "Monte seu catálogo",
    },
  },
  {
    kind: "feature",
    slug: "vendas-e-pedidos",
    title: "Vendas, pedidos e clientes",
    summary: "Leva o produto calculado direto para a venda e mantém o histórico.",
    status: "active",
    data: {
      audiences: ["empreendedoras-organizando-negocio", "marmitas-e-alimentos"],
      angle: "Da precificação à venda sem digitar tudo de novo",
      cta: "Organize a próxima venda",
    },
  },
  {
    kind: "feature",
    slug: "financeiro",
    title: "Financeiro e lucro real",
    summary: "Organiza entradas, saídas, despesas e visão do resultado.",
    status: "active",
    data: {
      audiences: ["empreendedoras-organizando-negocio", "beleza-e-servicos"],
      angle: "Faturamento não é lucro",
      cta: "Veja para onde o dinheiro vai",
    },
  },
  {
    kind: "feature",
    slug: "estoque-e-compras",
    title: "Estoque e compras",
    summary: "Acompanha materiais, fornecedores e reposição.",
    status: "active",
    data: {
      audiences: ["marmitas-e-alimentos", "artesaos-e-personalizados"],
      angle: "Comprar melhor protege sua margem",
      cta: "Organize seus insumos",
    },
  },
  {
    kind: "topic",
    slug: "preco-sem-chute",
    title: "Preço sem chute",
    summary: "Educação prática de custos, margem e preço.",
    status: "active",
    data: {
      pillars: ["custo", "mão de obra", "margem", "taxas", "desperdício"],
      formats: ["vídeo curto", "carrossel", "tutorial"],
    },
  },
  {
    kind: "topic",
    slug: "lucro-na-pratica",
    title: "Lucro na prática",
    summary: "Mostra por que vender muito não garante ganhar dinheiro.",
    status: "active",
    data: {
      pillars: ["lucro real", "fluxo de caixa", "ticket médio", "metas"],
      formats: ["história", "antes e depois", "checklist"],
    },
  },
  {
    kind: "topic",
    slug: "negocio-organizado",
    title: "Negócio organizado",
    summary: "Rotinas simples para sair do caderno e do retrabalho.",
    status: "active",
    data: {
      pillars: ["pedidos", "clientes", "estoque", "agenda"],
      formats: ["bastidores", "passo a passo", "lista"],
    },
  },
  {
    kind: "outreach",
    slug: "comunidades-whatsapp",
    title: "Comunidades de empreendedoras no WhatsApp",
    summary: "Chegar com diagnóstico ou material útil, sem spam.",
    status: "active",
    data: {
      where: "grupos locais, associações e cursos",
      approach: "pergunte qual parte do preço mais confunde e ofereça um checklist",
      cadence: "2 comunidades por semana",
      doNot: "entrar publicando link",
    },
  },
  {
    kind: "outreach",
    slug: "parcerias-profissionais",
    title: "Parcerias com professoras e consultoras",
    summary: "Demonstrações e conteúdo conjunto para públicos já formados.",
    status: "active",
    data: {
      where: "cursos de confeitaria, artesanato, beleza e Sebrae local",
      approach: "aula curta: do custo ao preço em 10 minutos",
      cadence: "5 contatos personalizados por semana",
    },
  },
  {
    kind: "outreach",
    slug: "comentarios-intencionais",
    title: "Comentários intencionais",
    summary: "Participar de conversas onde a dor de preço e organização já apareceu.",
    status: "active",
    data: {
      where: "posts e vídeos de nicho",
      approach: "responda a dúvida com uma microaula, sem convite prematuro",
      cadence: "15 minutos por dia",
    },
  },
  {
    kind: "campaign",
    slug: "primeiro-preco-certo",
    title: "Desafio: primeiro preço certo",
    summary: "Campanha de 7 dias para levar a pessoa ao primeiro cálculo e ao catálogo.",
    status: "planned",
    data: {
      objective: "activation",
      durationDays: 7,
      sequence: [
        "diagnóstico",
        "custos invisíveis",
        "mão de obra",
        "margem",
        "cálculo ao vivo",
        "catálogo",
        "convite",
      ],
      metric: "primeiro produto calculado",
    },
  },
  {
    kind: "campaign",
    slug: "piloto-midia-negocios-ativados",
    title: "Piloto de mídia: negócios ativados",
    summary:
      "Teste pequeno, liberado somente depois de funil, ficha da loja, calculadora e entrevistas estarem validados.",
    status: "planned",
    data: {
      objective: "activated_business",
      optimizationMetric: "cost_per_activated_business",
      audience: "confeiteiras-iniciantes",
      destination: "/landing/calculadora",
      utm: {
        source: "meta",
        medium: "paid_social",
        campaign: "piloto_negocios_ativados",
      },
      budget: "definir antes de ativar",
      readiness: [
        "eventos do funil validados em produção",
        "ficha da Google Play publicada sem Premium antigo",
        "calculadora pública validada",
        "10 entrevistas concluídas e sintetizadas",
      ],
      stopRule: "não escalar sem negócios ativados atribuídos",
    },
  },
];

const interviewSegments = [
  "confeiteiras-iniciantes",
  "confeiteiras-iniciantes",
  "marmitas-e-alimentos",
  "marmitas-e-alimentos",
  "artesaos-e-personalizados",
  "artesaos-e-personalizados",
  "beleza-e-servicos",
  "beleza-e-servicos",
  "empreendedoras-organizando-negocio",
  "empreendedoras-organizando-negocio",
] as const;

interviewSegments.forEach((audience, index) => {
  initialMarketingResources.push({
    kind: "interview",
    slug: `entrevista-${String(index + 1).padStart(2, "0")}`,
    title: `Entrevista ${String(index + 1).padStart(2, "0")} — ${audience}`,
    summary:
      "Conversa de descoberta sobre preço, organização, linguagem e decisão de teste.",
    status: "planned",
    data: {
      audience,
      participant: "a recrutar",
      consent: "pendente",
      durationMinutes: 30,
      script: [
        "Conte sobre a última vez que precisou definir ou revisar um preço.",
        "Como fez a conta e o que foi mais difícil?",
        "Que custos costuma esquecer ou ter dúvida se entram?",
        "O que acontece depois que decide o preço até concluir uma venda?",
        "Quais ferramentas usa hoje e onde precisa repetir informação?",
        "O que faria você testar ou abandonar uma solução como o Lucro Caseiro?",
      ],
      literalQuotes: [],
      pains: [],
      objections: [],
      currentAlternatives: [],
      evidence: "",
    },
  });
});

const weeklyIdeas = [
  [
    [
      "Segunda",
      "Erro",
      "Você vende, recebe e mesmo assim falta dinheiro?",
      "Reel/TikTok",
      "confeiteiras-iniciantes",
    ],
    [
      "Terça",
      "Tutorial",
      "3 custos que quase todo produto artesanal esquece",
      "Carrossel",
      "artesaos-e-personalizados",
    ],
    [
      "Quarta",
      "Demonstração",
      "Do ingrediente ao preço final em poucos minutos",
      "Reel/TikTok",
      "marmitas-e-alimentos",
    ],
    [
      "Quinta",
      "Objeção",
      "Preço do concorrente não paga as suas contas",
      "Reel",
      "beleza-e-servicos",
    ],
    [
      "Sexta",
      "Organização",
      "Cadastre uma vez e leve o produto para catálogo e venda",
      "Carrossel",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Sábado",
      "Bastidores",
      "Como revisar os números da semana sem planilha complicada",
      "Stories/Short",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Domingo",
      "Planejamento",
      "Escolha os 3 produtos que precisam de preço revisado",
      "Stories",
      "confeiteiras-iniciantes",
    ],
  ],
  [
    [
      "Segunda",
      "Mito",
      "Faturar muito não significa lucrar muito",
      "Reel/TikTok",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Terça",
      "Checklist",
      "Seu preço inclui embalagem, taxa e desperdício?",
      "Carrossel",
      "marmitas-e-alimentos",
    ],
    [
      "Quarta",
      "Demonstração",
      "Quanto cobrar por uma hora do seu trabalho?",
      "Reel/TikTok",
      "beleza-e-servicos",
    ],
    [
      "Quinta",
      "Comparação",
      "Copiar preço ou calcular preço: veja o que muda",
      "Carrossel",
      "artesaos-e-personalizados",
    ],
    [
      "Sexta",
      "Fluxo",
      "Produto calculado vira pedido sem cadastrar tudo outra vez",
      "Reel",
      "confeiteiras-iniciantes",
    ],
    [
      "Sábado",
      "Prova",
      "Antes e depois de organizar custos, preço e margem",
      "Stories",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Domingo",
      "Pesquisa",
      "Qual custo você mais esquece na hora de cobrar?",
      "Stories/Enquete",
      "confeiteiras-iniciantes",
    ],
  ],
  [
    [
      "Segunda",
      "Dor",
      "Agenda cheia e dinheiro curto: o preço pode ser o problema",
      "Reel/TikTok",
      "beleza-e-servicos",
    ],
    [
      "Terça",
      "Tutorial",
      "Como dividir o custo da receita por unidade sem errar",
      "Carrossel",
      "marmitas-e-alimentos",
    ],
    [
      "Quarta",
      "Demonstração",
      "Monte um kit e descubra se a promoção ainda dá lucro",
      "Reel/TikTok",
      "artesaos-e-personalizados",
    ],
    [
      "Quinta",
      "Objeção",
      "Meu cliente não paga esse preço: como aumentar valor percebido",
      "Carrossel",
      "confeiteiras-iniciantes",
    ],
    [
      "Sexta",
      "Catálogo",
      "Transforme o cadastro do produto em uma vitrine para o WhatsApp",
      "Reel",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Sábado",
      "Bastidores",
      "A rotina de 15 minutos que evita comprar insumo em excesso",
      "Short",
      "marmitas-e-alimentos",
    ],
    [
      "Domingo",
      "Planejamento",
      "Defina uma meta de lucro, não apenas de faturamento",
      "Stories",
      "empreendedoras-organizando-negocio",
    ],
  ],
  [
    [
      "Segunda",
      "Alerta",
      "Desconto sem conta pode apagar toda a sua margem",
      "Reel/TikTok",
      "artesaos-e-personalizados",
    ],
    [
      "Terça",
      "Checklist",
      "5 números para revisar antes de aumentar ou baixar o preço",
      "Carrossel",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Quarta",
      "Demonstração",
      "Do custo à venda: o fluxo completo em 30 segundos",
      "Reel/TikTok",
      "confeiteiras-iniciantes",
    ],
    [
      "Quinta",
      "Estratégia",
      "Como criar três opções e aumentar o ticket médio",
      "Carrossel",
      "beleza-e-servicos",
    ],
    [
      "Sexta",
      "Relacionamento",
      "Use o histórico de clientes para vender de novo",
      "Reel",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Sábado",
      "Resultado",
      "O que medir depois de publicar: salvamento, clique ou venda?",
      "Short",
      "empreendedoras-organizando-negocio",
    ],
    [
      "Domingo",
      "Fechamento",
      "O que funcionou este mês e qual teste vem agora?",
      "Stories/Template",
      "empreendedoras-organizando-negocio",
    ],
  ],
] as const;

weeklyIdeas.forEach((ideas, weekIndex) => {
  const week = weekIndex + 1;
  ideas.forEach(([day, angle, hook, format, audience], index) => {
    initialMarketingResources.push({
      kind: "content",
      slug: `semana-${week}-${day.toLowerCase()}`,
      title: `${day}: ${angle}`,
      summary: hook,
      status: "idea",
      data: {
        week,
        weekday: index + 1,
        audience,
        format,
        channels: format.includes("TikTok") ? ["instagram", "tiktok"] : ["instagram"],
        hook,
        structure: [
          "gancho",
          "problema real",
          "explicação simples",
          "exemplo",
          "próximo passo",
        ],
        cta:
          week === 1
            ? "Salve para revisar seu preço"
            : "Teste o Lucro Caseiro no seu próximo produto",
      },
    });
  });
});
