import {
  SceneMovementPlanSchema,
  type VideoPromptProjectInput,
} from "@lucro-caseiro/contracts";

export function completeVideoPromptProject(
  override: Partial<VideoPromptProjectInput> = {},
): VideoPromptProjectInput {
  return {
    brandId: "lucro-caseiro",
    title: "Precificação sem chute",
    format: "short-vertical",
    aspectRatio: "9:16",
    duration: 50,
    objective: "demonstrate-feature",
    customObjective: "",
    visualMode: "hybrid-character-interface",
    topicId: null,
    offerId: null,
    featureId: "precificacao-guiada",
    audienceId: null,
    funnelStage: "consideração",
    angle: "do chute à clareza",
    cta: "Conheça o Lucro Caseiro",
    destinationChannels: ["Instagram Reels"],
    targetTool: null,
    characterProfileId: null,
    voiceProfileId: null,
    contextVersion: "2026-08-12",
    status: "draft",
    scriptMode: "full",
    creativeBrief: {
      topic: "Como formar o preço de um bolo usando a precificação guiada",
      audience: "Confeiteiras que vendem, mas ainda calculam no caderno",
      painOrDesire: "Parar de vender sem saber se o preço cobre os custos",
      supportingFacts: [
        "A funcionalidade calcula custo, margem e preço a partir dos dados informados",
      ],
      restrictions: ["Não prometer aumento de lucro"],
      productEvidenceIds: ["captura-precificacao-01"],
    },
    direction: {
      character: {
        expression: "natural e responsiva",
        energy: "próxima",
        eyeContact: "alternado entre ação e câmera",
        gestures: "gestos naturais ligados à ação",
        posture: "relaxada e ativa",
        movementSpeed: "moderada",
      },
      voice: {
        language: "português brasileiro",
        vocalGender: "",
        apparentAge: "adulta",
        warmth: "calorosa",
        energy: "próxima",
        speed: "moderada",
        pauses: "pausas e respiração naturais",
        intonation: "conversacional, sem locução publicitária",
        savedVoice: "",
      },
      environment: "cozinha de produção acolhedora",
      camera: {
        focalLength: "35 mm equivalente",
        shot: "plano médio frontal",
        height: "altura dos olhos",
        angle: "frontal levemente lateral",
        movement: "movimento suave motivado pela ação",
        depthOfField: "fundo levemente desfocado",
        stability: "estável com respiração natural",
        speed: "moderada",
        perspective: "smartphone editorial plausível",
      },
      lighting: "luz natural lateral, suave e difusa",
      realism: "editorial",
    },
    scenes: [
      [0, 4, "gancho"],
      [4, 12, "contexto"],
      [12, 30, "demonstração"],
      [30, 40, "benefício"],
      [40, 50, "encerramento"],
    ].map(([startTime, endTime, narrativeRole], order) => ({
      order,
      startTime: Number(startTime),
      endTime: Number(endTime),
      narrativeRole: String(narrativeRole),
      characterPresent: order === 0 || order === 4,
      environment: "cozinha de produção acolhedora",
      action:
        order === 0
          ? "confeiteira confere caderno e celular"
          : "uma ação clara ligada à precificação",
      characterDirection: "postura ativa, expressão natural e gesto ligado ao objeto",
      cameraDirection: "plano médio frontal",
      lightingDirection: "luz natural lateral",
      dialogue: order === 0 ? "Você ainda calcula o preço no chute?" : "",
      narration: "",
      onScreenText: "",
      transition: "corte limpo",
      productEvidenceIds: order === 2 ? ["captura-precificacao-01"] : [],
      continuityNotes: "preservar roupa e posição dos objetos",
      movementPlan: SceneMovementPlanSchema.parse({}),
    })),
    ...override,
  };
}
