import {open} from './login.mjs';
const {b,p} = await open();
const W=1200;
await p.goto('http://localhost:8123/pricing'); await p.waitForTimeout(4000);
await p.getByLabel('Ingredientes ou material').pressSequentially('1800');
await p.getByLabel('Embalagem',{exact:true}).pressSequentially('600');
await p.getByLabel('Embalagem',{exact:true}).blur();
await p.waitForTimeout(W); await p.screenshot({path:'c1.png'});
await p.getByText('Continuar',{exact:true}).click(); await p.waitForTimeout(W);
await p.getByText('Seu trabalho',{exact:true}).click(); await p.waitForTimeout(800);
await p.getByText('Calcular pelo tempo').click(); await p.waitForTimeout(800);
await p.getByLabel('Tempo do lote').pressSequentially('180');
await p.getByLabel('Unidades por lote').pressSequentially('1');
await p.getByLabel('Valor da sua hora').pressSequentially('2000');
await p.getByLabel('Valor da sua hora').blur();
await p.waitForTimeout(W); await p.screenshot({path:'c2a.png'});
await p.getByText(/^Usar R\$ .* por unidade$/).click(); await p.waitForTimeout(800);
await p.getByText('Taxas e canal de venda').click(); await p.waitForTimeout(600);
await p.getByText('Confirmar venda sem taxa').click(); await p.waitForTimeout(W);
await p.getByText('Continuar',{exact:true}).click(); await p.waitForTimeout(W);
await p.getByLabel('Ganho desejado por unidade').pressSequentially('2600');
await p.getByLabel('Ganho desejado por unidade').blur();
await p.getByText('Composição do preço').click(); await p.waitForTimeout(W);
await p.screenshot({path:'c3.png'});
await b.close();
